// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v5.27.0
// source: failure.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	FailureService_StopRequests_FullMethodName      = "/protos.FailureService/StopRequests"
	FailureService_ReprocessRequests_FullMethodName = "/protos.FailureService/ReprocessRequests"
)

// FailureServiceClient is the client API for FailureService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type FailureServiceClient interface {
	StopRequests(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
	ReprocessRequests(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error)
}

type failureServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewFailureServiceClient(cc grpc.ClientConnInterface) FailureServiceClient {
	return &failureServiceClient{cc}
}

func (c *failureServiceClient) StopRequests(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, FailureService_StopRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *failureServiceClient) ReprocessRequests(ctx context.Context, in *RestoreRequest, opts ...grpc.CallOption) (*RestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RestoreResponse)
	err := c.cc.Invoke(ctx, FailureService_ReprocessRequests_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// FailureServiceServer is the server API for FailureService service.
// All implementations must embed UnimplementedFailureServiceServer
// for forward compatibility.
type FailureServiceServer interface {
	StopRequests(context.Context, *RestoreRequest) (*RestoreResponse, error)
	ReprocessRequests(context.Context, *RestoreRequest) (*RestoreResponse, error)
	mustEmbedUnimplementedFailureServiceServer()
}

// UnimplementedFailureServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedFailureServiceServer struct{}

func (UnimplementedFailureServiceServer) StopRequests(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method StopRequests not implemented")
}
func (UnimplementedFailureServiceServer) ReprocessRequests(context.Context, *RestoreRequest) (*RestoreResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ReprocessRequests not implemented")
}
func (UnimplementedFailureServiceServer) mustEmbedUnimplementedFailureServiceServer() {}
func (UnimplementedFailureServiceServer) testEmbeddedByValue()                        {}

// UnsafeFailureServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to FailureServiceServer will
// result in compilation errors.
type UnsafeFailureServiceServer interface {
	mustEmbedUnimplementedFailureServiceServer()
}

func RegisterFailureServiceServer(s grpc.ServiceRegistrar, srv FailureServiceServer) {
	// If the following call pancis, it indicates UnimplementedFailureServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&FailureService_ServiceDesc, srv)
}

func _FailureService_StopRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FailureServiceServer).StopRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FailureService_StopRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FailureServiceServer).StopRequests(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _FailureService_ReprocessRequests_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(FailureServiceServer).ReprocessRequests(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: FailureService_ReprocessRequests_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(FailureServiceServer).ReprocessRequests(ctx, req.(*RestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// FailureService_ServiceDesc is the grpc.ServiceDesc for FailureService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var FailureService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.FailureService",
	HandlerType: (*FailureServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "StopRequests",
			Handler:    _FailureService_StopRequests_Handler,
		},
		{
			MethodName: "ReprocessRequests",
			Handler:    _FailureService_ReprocessRequests_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "failure.proto",
}
