// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v3.19.6
// source: protos/request.proto

package protos

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateSnapshotRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Namespace     string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceName   string                 `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	RegistryName  string                 `protobuf:"bytes,3,opt,name=registryName,proto3" json:"registryName,omitempty"`
	LatestRequest uint64                 `protobuf:"varint,4,opt,name=latestRequest,proto3" json:"latestRequest,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSnapshotRequest) Reset() {
	*x = CreateSnapshotRequest{}
	mi := &file_protos_request_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSnapshotRequest) ProtoMessage() {}

func (x *CreateSnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_request_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSnapshotRequest.ProtoReflect.Descriptor instead.
func (*CreateSnapshotRequest) Descriptor() ([]byte, []int) {
	return file_protos_request_proto_rawDescGZIP(), []int{0}
}

func (x *CreateSnapshotRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *CreateSnapshotRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *CreateSnapshotRequest) GetRegistryName() string {
	if x != nil {
		return x.RegistryName
	}
	return ""
}

func (x *CreateSnapshotRequest) GetLatestRequest() uint64 {
	if x != nil {
		return x.LatestRequest
	}
	return 0
}

type ReplySnapshotRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Namespace      string                 `protobuf:"bytes,1,opt,name=namespace,proto3" json:"namespace,omitempty"`
	ServiceName    string                 `protobuf:"bytes,2,opt,name=serviceName,proto3" json:"serviceName,omitempty"`
	RegistryName   string                 `protobuf:"bytes,3,opt,name=registryName,proto3" json:"registryName,omitempty"`
	SnapshotStatus string                 `protobuf:"bytes,4,opt,name=snapshotStatus,proto3" json:"snapshotStatus,omitempty"`
	LatestRequest  uint64                 `protobuf:"varint,5,opt,name=latestRequest,proto3" json:"latestRequest,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReplySnapshotRequest) Reset() {
	*x = ReplySnapshotRequest{}
	mi := &file_protos_request_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReplySnapshotRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReplySnapshotRequest) ProtoMessage() {}

func (x *ReplySnapshotRequest) ProtoReflect() protoreflect.Message {
	mi := &file_protos_request_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReplySnapshotRequest.ProtoReflect.Descriptor instead.
func (*ReplySnapshotRequest) Descriptor() ([]byte, []int) {
	return file_protos_request_proto_rawDescGZIP(), []int{1}
}

func (x *ReplySnapshotRequest) GetNamespace() string {
	if x != nil {
		return x.Namespace
	}
	return ""
}

func (x *ReplySnapshotRequest) GetServiceName() string {
	if x != nil {
		return x.ServiceName
	}
	return ""
}

func (x *ReplySnapshotRequest) GetRegistryName() string {
	if x != nil {
		return x.RegistryName
	}
	return ""
}

func (x *ReplySnapshotRequest) GetSnapshotStatus() string {
	if x != nil {
		return x.SnapshotStatus
	}
	return ""
}

func (x *ReplySnapshotRequest) GetLatestRequest() uint64 {
	if x != nil {
		return x.LatestRequest
	}
	return 0
}

type AckResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Response      bool                   `protobuf:"varint,1,opt,name=response,proto3" json:"response,omitempty"`
	Error         string                 `protobuf:"bytes,2,opt,name=error,proto3" json:"error,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckResponse) Reset() {
	*x = AckResponse{}
	mi := &file_protos_request_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckResponse) ProtoMessage() {}

func (x *AckResponse) ProtoReflect() protoreflect.Message {
	mi := &file_protos_request_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckResponse.ProtoReflect.Descriptor instead.
func (*AckResponse) Descriptor() ([]byte, []int) {
	return file_protos_request_proto_rawDescGZIP(), []int{2}
}

func (x *AckResponse) GetResponse() bool {
	if x != nil {
		return x.Response
	}
	return false
}

func (x *AckResponse) GetError() string {
	if x != nil {
		return x.Error
	}
	return ""
}

var File_protos_request_proto protoreflect.FileDescriptor

const file_protos_request_proto_rawDesc = "" +
	"\n" +
	"\x14protos/request.proto\x12\x06protos\"\xa1\x01\n" +
	"\x15CreateSnapshotRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12 \n" +
	"\vserviceName\x18\x02 \x01(\tR\vserviceName\x12\"\n" +
	"\fregistryName\x18\x03 \x01(\tR\fregistryName\x12$\n" +
	"\rlatestRequest\x18\x04 \x01(\x04R\rlatestRequest\"\xc8\x01\n" +
	"\x14ReplySnapshotRequest\x12\x1c\n" +
	"\tnamespace\x18\x01 \x01(\tR\tnamespace\x12 \n" +
	"\vserviceName\x18\x02 \x01(\tR\vserviceName\x12\"\n" +
	"\fregistryName\x18\x03 \x01(\tR\fregistryName\x12&\n" +
	"\x0esnapshotStatus\x18\x04 \x01(\tR\x0esnapshotStatus\x12$\n" +
	"\rlatestRequest\x18\x05 \x01(\x04R\rlatestRequest\"?\n" +
	"\vAckResponse\x12\x1a\n" +
	"\bresponse\x18\x01 \x01(\bR\bresponse\x12\x14\n" +
	"\x05error\x18\x02 \x01(\tR\x05error2\x8e\x01\n" +
	"\x12SnapshotRPCService\x12<\n" +
	"\x06Create\x12\x1d.protos.CreateSnapshotRequest\x1a\x13.protos.AckResponse\x12:\n" +
	"\x05Reply\x12\x1c.protos.ReplySnapshotRequest\x1a\x13.protos.AckResponseB-Z+github.com/rhmuller/interceptor-grpc/protosb\x06proto3"

var (
	file_protos_request_proto_rawDescOnce sync.Once
	file_protos_request_proto_rawDescData []byte
)

func file_protos_request_proto_rawDescGZIP() []byte {
	file_protos_request_proto_rawDescOnce.Do(func() {
		file_protos_request_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_request_proto_rawDesc), len(file_protos_request_proto_rawDesc)))
	})
	return file_protos_request_proto_rawDescData
}

var file_protos_request_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protos_request_proto_goTypes = []any{
	(*CreateSnapshotRequest)(nil), // 0: protos.CreateSnapshotRequest
	(*ReplySnapshotRequest)(nil),  // 1: protos.ReplySnapshotRequest
	(*AckResponse)(nil),           // 2: protos.AckResponse
}
var file_protos_request_proto_depIdxs = []int32{
	0, // 0: protos.SnapshotRPCService.Create:input_type -> protos.CreateSnapshotRequest
	1, // 1: protos.SnapshotRPCService.Reply:input_type -> protos.ReplySnapshotRequest
	2, // 2: protos.SnapshotRPCService.Create:output_type -> protos.AckResponse
	2, // 3: protos.SnapshotRPCService.Reply:output_type -> protos.AckResponse
	2, // [2:4] is the sub-list for method output_type
	0, // [0:2] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_protos_request_proto_init() }
func file_protos_request_proto_init() {
	if File_protos_request_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_request_proto_rawDesc), len(file_protos_request_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protos_request_proto_goTypes,
		DependencyIndexes: file_protos_request_proto_depIdxs,
		MessageInfos:      file_protos_request_proto_msgTypes,
	}.Build()
	File_protos_request_proto = out.File
	file_protos_request_proto_goTypes = nil
	file_protos_request_proto_depIdxs = nil
}
