// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             v3.19.6
// source: protos/request.proto

package protos

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	SnapshotRPCService_Create_FullMethodName = "/protos.SnapshotRPCService/Create"
	SnapshotRPCService_Reply_FullMethodName  = "/protos.SnapshotRPCService/Reply"
)

// SnapshotRPCServiceClient is the client API for SnapshotRPCService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type SnapshotRPCServiceClient interface {
	Create(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*AckResponse, error)
	Reply(ctx context.Context, in *ReplySnapshotRequest, opts ...grpc.CallOption) (*AckResponse, error)
}

type snapshotRPCServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewSnapshotRPCServiceClient(cc grpc.ClientConnInterface) SnapshotRPCServiceClient {
	return &snapshotRPCServiceClient{cc}
}

func (c *snapshotRPCServiceClient) Create(ctx context.Context, in *CreateSnapshotRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, SnapshotRPCService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *snapshotRPCServiceClient) Reply(ctx context.Context, in *ReplySnapshotRequest, opts ...grpc.CallOption) (*AckResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AckResponse)
	err := c.cc.Invoke(ctx, SnapshotRPCService_Reply_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// SnapshotRPCServiceServer is the server API for SnapshotRPCService service.
// All implementations must embed UnimplementedSnapshotRPCServiceServer
// for forward compatibility.
type SnapshotRPCServiceServer interface {
	Create(context.Context, *CreateSnapshotRequest) (*AckResponse, error)
	Reply(context.Context, *ReplySnapshotRequest) (*AckResponse, error)
	mustEmbedUnimplementedSnapshotRPCServiceServer()
}

// UnimplementedSnapshotRPCServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedSnapshotRPCServiceServer struct{}

func (UnimplementedSnapshotRPCServiceServer) Create(context.Context, *CreateSnapshotRequest) (*AckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedSnapshotRPCServiceServer) Reply(context.Context, *ReplySnapshotRequest) (*AckResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Reply not implemented")
}
func (UnimplementedSnapshotRPCServiceServer) mustEmbedUnimplementedSnapshotRPCServiceServer() {}
func (UnimplementedSnapshotRPCServiceServer) testEmbeddedByValue()                            {}

// UnsafeSnapshotRPCServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to SnapshotRPCServiceServer will
// result in compilation errors.
type UnsafeSnapshotRPCServiceServer interface {
	mustEmbedUnimplementedSnapshotRPCServiceServer()
}

func RegisterSnapshotRPCServiceServer(s grpc.ServiceRegistrar, srv SnapshotRPCServiceServer) {
	// If the following call pancis, it indicates UnimplementedSnapshotRPCServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&SnapshotRPCService_ServiceDesc, srv)
}

func _SnapshotRPCService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateSnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotRPCServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotRPCService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotRPCServiceServer).Create(ctx, req.(*CreateSnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _SnapshotRPCService_Reply_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReplySnapshotRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(SnapshotRPCServiceServer).Reply(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: SnapshotRPCService_Reply_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(SnapshotRPCServiceServer).Reply(ctx, req.(*ReplySnapshotRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// SnapshotRPCService_ServiceDesc is the grpc.ServiceDesc for SnapshotRPCService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var SnapshotRPCService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "protos.SnapshotRPCService",
	HandlerType: (*SnapshotRPCServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _SnapshotRPCService_Create_Handler,
		},
		{
			MethodName: "Reply",
			Handler:    _SnapshotRPCService_Reply_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "protos/request.proto",
}
